### ISSUE TITLE
NPE in RecorderService.unregister

### ISSUE THREAD

**Issue by csmith** [csmith/ContextApi#59]
```
Caused by: java.lang.NullPointerException
at uk.co.md87.android.activityrecorder.RecorderService.unregister(RecorderService.java:190)
at uk.co.md87.android.activityrecorder.RecorderService.onDestroy(RecorderService.java:203)
at android.app.ActivityThread.handleStopService(ActivityThread.java:2797)
```

**Comment by csmith** [comment]
RecorderService improvements

Fix NPE when destroying after only binding. Closed by 37f4cf698a4448c3c59524aa9721b8ae8562301a
Potential fix for not logging data when screen is off
